### ISSUE TITLE
where should I put pandoc.exe?

### ISSUE THREAD

**Issue by retsyo** [gpoore/codebraid#13]
pandoc.exe is in one directory of my `PATH` environmental variant, so I can run pandoc.exe under any directory in the dos console
however, codebraid can not find pandoc.exe. So where should I put pandoc.exe? Or should codebraid consider `PATH`?

thanks

**Comment by gpoore** [comment]
Having pandoc.exe on your `PATH` should work. What error message are you getting? Which version of Windows are you using? Which version of Python? It's been working fine for me under Windows 10 with Python 3.7, but it's possible there's an issue with an earlier version or combination of Windows or Python.
