### ISSUE TITLE
Issue when combining html comments and empty list items

### ISSUE THREAD

**Issue by Synthetica9** [gpoore/codebraid#16]
# Minimal failing example

## Input:

```
1.  <!-- -->
```

## Output:

```
1.  `{.codebraid--temp format="html"}     <!-- -->`
```

Expected output: same as input.

**Comment by gpoore** [comment]
That is working for me when converting to Markdown or to HTML with Pandoc 2.9.1.1. Can you give me the Pandoc and Codebraid versions you are using, plus the command you are running?

**Comment by Synthetica9** [comment]
Oh, I didn't know a new Pandoc version was out. I'll update my installation and see if that helps.
