### ISSUE TITLE
Non-zero exit code when exceptions were issued?

### ISSUE THREAD

**Issue by grwlf** [gpoore/codebraid#24]
Could you please consider adding a feature of returning non-zero exit codes if one or more exceptions were issued? It would help e.g in using codebraid in Makefiles.

Currently we are to grep the output documents for magic words from stack traces which is a bit fragile.

**Comment by gpoore** [comment]
That's a good suggestion. I'll add that in the next version.

**Comment by gpoore** [comment]
The latest release adds exit codes. Based on the exit code, it is possible to determine whether there were errors or warnings, and whether they were primarily related to the document or to code execution. Details: https://github.com/gpoore/codebraid/blob/master/CHANGELOG.md. I'll update the documentation soon. I suspect there may be a need to add a command-line option to disable non-zero exit codes, but we'll see what happens.
