### ISSUE TITLE
Jupyter Kernel timeout Option

### ISSUE THREAD

**Issue by amichuda** [gpoore/codebraid#30]
I'm creating some tables in codebraid and it takes a while, but after a minute, I get the error:

```
Jupyter kernel "python3" timed out during execution
```

I checked the code and I think it might have something to do with:

https://github.com/gpoore/codebraid/blob/f4b98af12066fc504a096fd73ab83741470bc57e/codebraid/codeprocessors/base.py#L1133

Would it be possible to let the jupyter kernel timeout be an option set when running codebraid? I can open a pull request, but I'm not sure whether you would want it exposed in `Converter` or somewhere else?

**Comment by gpoore** [comment]
In the last commit, I've added a `jupyter_timeout` option that you can specify in the first code chunk in a session, right next to `jupyter_kernel`. It will probably make sense to allow this to be set elsewhere eventually, but there isn't a good way to set options in a centralized location yet.

**Comment by amichuda** [comment]
Ah! My apologies, I didn't see that option. Thank you!

**Comment by gpoore** [comment]
You couldn't have seen that option, because I just added it after you opened the issue.
