### ISSUE TITLE
Reading from stdin

### ISSUE THREAD

**Issue by timothymillar** [gpoore/codebraid#33]
It would be useful if codebraid  could read directly from stdin.
This would allow for piping the output of a pandoc command into codebraid e.g.:

```bash
pandoc --filter <filter> --to markdown | codebraid pandoc ...
```

A common way to implement this in `argparse` is to use `-` to specify reading from stdin e.g.:

```bash
pandoc --filter <filter> --to markdown | codebraid pandoc - -o result.md
```

**Comment by gpoore** [comment]
Thanks for the suggestion! This should work with the last commit. I'll put a new version on PyPI as soon as I address a few other issues.
