### ISSUE TITLE
conversion from md to PDF gives StopIteration when escaping italics

### ISSUE THREAD

**Issue by amichuda** [gpoore/codebraid#36]
When converting from markdown to PDF, and you escape asterisks, you get a StopIteration error. For example:

```
A\*
```

and run `codebraid pandoc -o test.pdf test.md`

**Comment by gpoore** [comment]
The algorithm that synchronizes code with line numbers in the source document was having issues with backslash escapes. The last commit simplifies this process and should prevent these sorts of issues in the future. I'm trying to wrap up a few additional issues, and will then put a new version up on PyPI.
