### ISSUE TITLE
Errors with pandoc 2.11

### ISSUE THREAD

**Issue by denismaier** [gpoore/codebraid#40]
I'm getting errors with pandoc 2.11. Codebraid complains about this version with the error message that pandoc version >= 2.4 is required...

**Comment by gpoore** [comment]
I believe this is fixed in the dev version on GitHub. I haven't had time to get a new release out that includes this and other recent changes...I'll try to do that soon.

**Comment by gusbemacbe** [comment]
Any news? I still have this problem.

**Comment by gpoore** [comment]
@gusbemacbe v0.5.0 is now on PyPI and includes the fix for pandoc 2.10+ compatibility, If you still have issues after upgrading, please open a new issue.
