### ISSUE TITLE
--citeproc Pandoc option

### ISSUE THREAD

**Issue by draustin** [gpoore/codebraid#42]
Is there a reason that --citeproc is omitted from PANDOC_OPTIONS? I got it working along with --bibliography by adding

> ('-C', '--citeproc'): 0

to PANDOC_OPTIONS.

**Comment by gpoore** [comment]
It looks like `--citeproc` was added in pandoc 2.11, which was after the last time I updated support for pandoc options. I'll add that to the next release. Thanks for pointing this out!
