### ISSUE TITLE
Would you consider supporting Sagemath ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [gpoore/codebraid#5]
My experience with [Pythontex](https://github.com/gpoore/pythontex) being mostly positive, I'd like to do similar things with Markdown, which is more and more prevalent.

Would you consider adding support for [Sagemath](http://www.sagemath.org/) ?

**Comment by gpoore** [comment]
I've added support with the most recent commit.

I have only tested Python-type functionality, so if you run across any issues with more Sage-specific usage, let me know. I also haven't tried using a Sage Jupyter kernel, though that should just work.
