### ISSUE TITLE
Plots in output

### ISSUE THREAD

**Issue by lordflaron** [gpoore/codebraid#6]
Hi,

First off, thank you for this awesome project.

Your python example in GitHub shows that matplotlib plots needed to be inserted through markdown after being created in python, but your Scipy 2019 article has the figure being created without that step. Does that have something to do with calling the Jupyter kernel option? Can you have that output display as png so that it can be used with pandoc-fignos?

Thank you

**Comment by gpoore** [comment]
You are correct. Currently, figures are only included automatically when a Jupyter kernel is used rather than the default, built-in code execution system. I've modified the examples to clarify this. Thanks for pointing this out.

I'll address pandoc-fignos in #7.
